{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "792d0cf5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "\n",
    "class ComparisonPlot:\n",
    "    def __init__(self, cff, x_range,  folder_path, true_color='r', fit_color='b', point_size=5, show_error_bars=True, show_mean_points=True, show_y_range=False, save_path=None, show_plot=True, y_range=None, file_name=\"comparison_plot\", true_value_path=None):\n",
    "        self.cff = cff\n",
    "        self.x_range = x_range\n",
    "        self.y_range = y_range\n",
    "        self.folder_path = folder_path\n",
    "        self.fit_color = fit_color\n",
    "        self.true_color = true_color\n",
    "        self.point_size = point_size\n",
    "        self.show_error_bars = show_error_bars\n",
    "        self.show_mean_points = show_mean_points\n",
    "        self.show_y_range = show_y_range\n",
    "        self.save_path = save_path\n",
    "        self.show_plot = show_plot\n",
    "        self.file_name = file_name\n",
    "        self.true_value_path = true_value_path if true_value_path is not None else \"pseudo_KM15.csv\"\n",
    "        \n",
    "    def plot(self):\n",
    "        # Find all the files in the folder_path that start with \"bySetCFFs\"\n",
    "        files = [f for f in os.listdir(self.folder_path) if f.startswith(\"bySetCFFs\")]\n",
    "\n",
    "        # Read the CSV files into a list of DataFrames\n",
    "        dfs = [pd.read_csv(os.path.join(self.folder_path, f), index_col=0) for f in files]\n",
    "\n",
    "        # Count the number of files read through the folder\n",
    "        num_files = len(dfs)\n",
    "\n",
    "        # Concatenate the DataFrames along the third dimension\n",
    "        array_3d = np.stack([df.values for df in dfs], axis=-1)\n",
    "\n",
    "        # Compute the mean and standard deviation along the third dimension\n",
    "        array_mean = np.mean(array_3d, axis=-1)\n",
    "        array_stdev = np.std(array_3d, axis=-1)\n",
    "\n",
    "        # Convert the resulting NumPy arrays into DataFrames and set the column and index names\n",
    "        df_mean = pd.DataFrame(array_mean, columns=dfs[0].columns, index=dfs[0].index)\n",
    "        df_stdev = pd.DataFrame(array_stdev, columns=dfs[0].columns, index=dfs[0].index)\n",
    "\n",
    "        # Shift the index of both DataFrames by 1\n",
    "        df_mean.index = df_mean.index + 1\n",
    "        df_stdev.index = df_stdev.index + 1\n",
    "        \n",
    "        # Convert the mean and stdev arrays to DataFrames and set the column and index names\n",
    "        df_mean.columns = ['ReH', 'ReE', 'ReHTilde', 'dvcs']\n",
    "        df_stdev.columns = ['ReH', 'ReE', 'ReHTilde', 'dvcs']\n",
    "\n",
    "        # Filter the data based on x range\n",
    "        result = pd.read_csv(self.true_value_path)\n",
    "        result_filtered = result[(result['#Set'] >= self.x_range[0]) & (result['#Set'] <= self.x_range[1])]\n",
    "        df_filtered = df_mean[(df_mean.index >= self.x_range[0]) & (df_mean.index <= self.x_range[1])].reset_index()\n",
    "        y_err_filtered = df_stdev[(df_stdev.index >= self.x_range[0]) & (df_stdev.index <= self.x_range[1])][self.cff].to_numpy()\n",
    "\n",
    "        # Plot filtered mean and filtered errorbars\n",
    "        if self.show_mean_points:\n",
    "            plt.scatter(np.array(df_filtered.iloc[:, 0]), np.array(df_filtered[self.cff]), color=self.fit_color, s=self.point_size)\n",
    "        if self.show_error_bars:\n",
    "            plt.errorbar(np.array(df_filtered.iloc[:, 0]), np.array(df_filtered[self.cff]), color=self.fit_color, yerr=y_err_filtered, fmt='none', capsize=3, label = 'Fitted Values')\n",
    "\n",
    "        # Plot x against y\n",
    "        plt.scatter(result_filtered['#Set'], result_filtered[self.cff], color=self.true_color, s=self.point_size, label = 'True Values')\n",
    "\n",
    "        # Modify the plot title based on the number of files and column_y\n",
    "        plt.title(f'{self.cff} Comparison Plot for {num_files} Replicas')\n",
    "        plt.legend()\n",
    "        plt.xlabel('Bin')\n",
    "        plt.ylabel(f'{self.cff}')\n",
    "        \n",
    "        #Filter the plot based on y range\n",
    "        if self.show_y_range:\n",
    "            plt.ylim(self.y_range)\n",
    "        \n",
    "        #Saves plot to path and sets default name of file\n",
    "        if self.save_path is not None:\n",
    "            self.file_name = f\"{self.file_name}_{self.cff}_{num_files}_replicas\"\n",
    "            plt.savefig(os.path.join(self.save_path, self.file_name))\n",
    "\n",
    "        #Show plot\n",
    "        if self.show_plot:\n",
    "            plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a41737b1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
